name: Manual Auto PR (quan ⇄ phat)

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Branch to merge from"
        required: true
        default: "quan"
        type: choice
        options:
          - quan
          - phat

      target_branch:
        description: "Branch to merge into"
        required: true
        default: "phat"
        type: choice
        options:
          - phat
          - quan

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.inputs.source_branch }}
          destination_branch: ${{ github.event.inputs.target_branch }}
          pr_title: "Auto-merge: ${{_
